kubeclt create -f voting-app-pod.yml
kubeclt create -f voting-app-service.yml
kubeclt create -f redis-pod.yml
kubeclt create -f redis-service.yml
kubeclt create -f postgres-pod.yml
kubeclt create -f postgres-service.yml
kubeclt create -f worker-app-pod.yml
kubeclt create -f result-app-pod.yml
kubeclt create -f result-app-service.yml