apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    env: demo
    app: my-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      ports:
        - containerPort: 80
