apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: redis-replication-controller
spec:
  replicas: 6
  selector:
    app: redis
  template:
    metadata:
      labels:
        app: redis
        name: redis-pod
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 80
